using System;
using System.Collections.Generic;

namespace SkiResortTycoon.Core
{
    /// <summary>
    /// Male first and last names for skiers. 300 of each = 90,000 unique combinations.
    /// Each skier gets a random first + random last. No repeats.
    /// </summary>
    public static class SkierNames
    {
        private static readonly Random _rng = new Random();
        private static readonly HashSet<string> _usedNames = new HashSet<string>();
        private static readonly string[] FirstNames =
        {
            "James", "John", "Robert", "Michael", "David", "William", "Richard", "Joseph", "Thomas", "Charles",
            "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua",
            "Kenneth", "Kevin", "Brian", "George", "Timothy", "Ronald", "Edward", "Jason", "Jeffrey", "Jacob",
            "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott", "Brandon", "Benjamin",
            "Samuel", "Raymond", "Gregory", "Frank", "Alexander", "Patrick", "Jack", "Dennis", "Jerry", "Tyler",
            "Aaron", "Jose", "Adam", "Nathan", "Henry", "Douglas", "Zachary", "Peter", "Kyle", "Noah",
            "Ethan", "Jeremy", "Walter", "Christian", "Keith", "Roger", "Terry", "Austin", "Sean", "Gerald",
            "Carl", "Dylan", "Harold", "Lawrence", "Arthur", "Jordan", "Jesse", "Bryan", "Billy", "Bruce",
            "Gabriel", "Joe", "Logan", "Albert", "Willie", "Alan", "Eugene", "Russell", "Vincent", "Philip",
            "Bobby", "Johnny", "Bradley", "Roy", "Ralph", "Randy", "Howard", "Carlos", "Louis", "Harry",
            "Wayne", "Stanley", "Leonard", "Nathaniel", "Manuel", "Rodney", "Curtis", "Norman", "Allen", "Marvin",
            "Glenn", "Jeffery", "Travis", "Lee", "Melvin", "Alfred", "Francis", "Jesus", "Herbert", "Frederick",
            "Ray", "Joel", "Edwin", "Don", "Eddie", "Ricky", "Troy", "Randall", "Barry", "Bernard",
            "Mario", "Leroy", "Francisco", "Marcus", "Theodore", "Clifford", "Miguel", "Oscar", "Jay", "Jim",
            "Tom", "Calvin", "Alex", "Jon", "Ronnie", "Bill", "Lloyd", "Tommy", "Leon", "Derek",
            "Warren", "Darren", "Lonnie", "Lance", "Cody", "Julio", "Kelly", "Kurt", "Allan", "Nelson",
            "Guy", "Clayton", "Hugh", "Max", "Dwayne", "Dwight", "Armando", "Felix", "Jimmie", "Everett",
            "Ian", "Wallace", "Ken", "Bob", "Jaime", "Casey", "Alfredo", "Alberto", "Dave", "Ivan",
            "Johnnie", "Sidney", "Byron", "Julian", "Isaac", "Morris", "Clifton", "Willard", "Daryl", "Ross",
            "Virgil", "Andy", "Marshall", "Salvador", "Perry", "Kirk", "Sergio", "Marion", "Tracy", "Seth",
            "Kent", "Terrance", "Rene", "Eduardo", "Terrell", "Enrique", "Fredrick", "Wade", "Stuart", "Chad",
            "Tony", "Luis", "Mike", "Lester", "Alvin", "Orlando", "Cecil", "Dominic", "Reginald", "Phil",
            "Shawn", "Clyde", "Glen", "Hector", "Sam", "Wilbert", "Jasper", "Neal", "Ted", "Milton",
            "Raul", "Ben", "Chester", "Duane", "Franklin", "Andre", "Elmer", "Brad", "Ron", "Mitchell",
            "Roland", "Arnold", "Harvey", "Jared", "Adrian", "Karl", "Cory", "Claude", "Erik", "Darryl",
            "Jamie", "Neil", "Jessie", "Javier", "Fernando", "Clinton", "Mathew", "Tyrone", "Owen", "Connor",
            "Declan", "Finn", "Liam", "Mason", "Lucas", "Oliver", "Aiden", "Elijah", "Grayson", "Hunter",
            "Jackson", "Levi", "Miles", "Nolan", "Parker", "Quinn", "Reid", "Sawyer", "Tucker", "Vance",
            "Xander", "Zane", "Brett", "Cole", "Dane", "Evan", "Grant", "Heath", "Jace", "Kade",
            "Lane", "Mack", "Nash", "Otis", "Preston", "Quincy", "Reed", "Sage", "Tate", "Vaughn",
            "Wes", "Xavier", "Zach", "Cameron", "Colton", "Brody", "Caden", "Jaxon", "Cooper", "Lincoln",
            "Gavin", "Brayden", "Asher", "Colin", "Blake", "Devin", "Garrett", "Holden", "Kai", "Landon",
            "Maddox", "Reece", "Spencer", "Trey", "Weston", "Zander", "Brock", "Chase", "Dexter", "Emmett",
            "Griffin", "Hayden", "Jett", "Knox", "Luca", "Milo", "Nico", "Peyton", "Rhett", "Silas",
            "Tyson", "Zeke", "Brady", "Cruz", "Dallas", "Ezra", "Gage", "Hudson", "Odin", "Phoenix",
            "Rocco", "Wyatt", "Beckett", "Drew", "Ezekiel", "Harrison", "Jensen", "Kellan", "Lucian", "Maxwell",
            "Nixon", "Orion", "Porter", "Ryder", "Sullivan", "Tristan", "Wesley", "Zion", "Bentley", "Crew",
            "Dawson", "Easton", "Graham", "Hendrix", "Antonio", "Juan", "Craig", "Victor", "Martin", "Ernest",
            "Clarence", "Chris", "Earl", "Jimmy", "Todd", "Floyd", "Darrell", "Gene", "Derrick", "Rick",
            "Andre", "Lorenzo", "Cedric", "Wendell", "Felix", "Willard", "Darin", "Neal", "Grady", "Max",
            "Rudy", "Colby", "Desmond", "Robin", "Loren", "Delbert", "Lowell", "Garland", "Sherman",
            "Stefan", "Quentin", "Hunter", "Kendrick", "Freddy", "Winfred", "Sterling", "Chance", "Bryce", "Dillon"
        };

        private static readonly string[] LastNames =
        {
            "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
            "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
            "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
            "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
            "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts",
            "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker", "Cruz", "Edwards", "Collins", "Reyes",
            "Stewart", "Morris", "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper",
            "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson",
            "Wood", "Watson", "Brooks", "Bennett", "Gray", "James", "Hughes", "Price", "Myers", "Long",
            "Foster", "Sanders", "Ross", "Powell", "Sullivan", "Russell", "Jenkins", "Perry", "Butler", "Barnes",
            "Fisher", "Henderson", "Coleman", "Simmons", "Patterson", "Jordan", "Reynolds", "Hamilton", "Graham", "Wallace",
            "Griffin", "West", "Cole", "Hayes", "Chavez", "Gibson", "Bryant", "Ellis", "Stevens", "Murray",
            "Ford", "Marshall", "Owens", "McDonald", "Harrison", "Ruiz", "Kennedy", "Wells", "Alvarez", "Woods",
            "Mendoza", "Castillo", "Olson", "Webb", "Washington", "Tucker", "Freeman", "Burns", "Henry", "Vasquez",
            "Snyder", "Simpson", "Crawford", "Jimenez", "Porter", "Mason", "Shaw", "Gordon", "Wagner", "Hunter",
            "Romero", "Hicks", "Dixon", "Hunt", "Palmer", "Robertson", "Black", "Holmes", "Stone", "Meyer",
            "Boyd", "Mills", "Warren", "Fox", "Rose", "Rice", "Moreno", "Schmidt", "Patel", "Ferguson",
            "Nichols", "Herrera", "Medina", "Ryan", "Fernandez", "Weaver", "Daniels", "Stephens", "Gardner", "Payne",
            "Kelley", "Dunn", "Pierce", "Arnold", "Tran", "Spencer", "Peters", "Hawkins", "Grant", "Hansen",
            "Castro", "Hoffman", "Hart", "Elliott", "Cunningham", "Knight", "Bradley", "Carroll", "Hudson", "Duncan",
            "Armstrong", "Berry", "Andrews", "Johnston", "Ray", "Lane", "Riley", "Carpenter", "Perkins", "Aguilar",
            "Silva", "Richards", "Willis", "Matthews", "Chapman", "Lawrence", "Garza", "Vargas", "Watkins", "Wheeler",
            "Larson", "Carlson", "Harper", "George", "Greene", "Burke", "Guzman", "Morrison", "Munoz", "Jacobs",
            "O'Brien", "Lawson", "Franklin", "Lynch", "Bishop", "Carr", "Salazar", "Austin", "Mendez", "Gilbert",
            "Jensen", "Williamson", "Montgomery", "Harvey", "Oliver", "Howell", "Dean", "Hanson", "Weber", "Garrett",
            "Sims", "Burton", "Fuller", "Soto", "McCoy", "Welch", "Chen", "Schultz", "Walters", "Reid",
            "Fields", "Walsh", "Little", "Fowler", "Bowman", "Davidson", "May", "Day", "Schneider", "Newman",
            "Brewer", "Lucas", "Holland", "Wong", "Banks", "Santos", "Curtis", "Pearson", "Delgado", "Valdez",
            "Pennington", "Rios", "Cannon", "Chandler", "Blair", "Daniel", "Cross", "Simon", "Dennis", "O'Connor",
            "Quinn", "Gross", "Navarro", "Moss", "Fitzgerald", "Doyle", "McLaughlin", "Rojas", "Rodgers", "Stevenson",
            "Singh", "Zhang", "Yang", "Chen", "Liu", "Huang", "Kumar", "Xu", "Sun", "Li",
            "Zhao", "Wu", "Choi", "Park", "Kim", "Nguyen", "Tran", "Le", "Pham", "Hoang",
            "Phan", "Vu", "Dang", "Bui", "Do", "Ngo", "Ly", "Truong", "Vo", "Phung",
            "Patel", "Shah", "Mehta", "Joshi", "Desai", "Reddy", "Rao", "Khan", "Ali", "Hassan",
            "Hussein", "Ahmed", "Malik", "Ibrahim", "Omar", "Yusuf", "Hussein", "Abbas", "Farooq", "Rashid",
            "Schmidt", "Mueller", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann", "Koch",
            "Richter", "Klein", "Wolf", "Schroeder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Krueger", "Hartmann",
            "Lange", "Schmitt", "Werner", "Schmid", "Krause", "Meier", "Lehmann", "Huber", "Mayer", "Herrmann",
            "Köhler", "Walter", "König", "Fuchs", "Kaiser", "Lang", "Weiss", "Peters", "Scholz", "Möller",
            "Berger", "Stark", "Jäger", "Otto", "Simon", "Frank", "Schubert", "Vogel", "Friedrich", "Günther",
            "Kramer", "Frank", "Bauer", "Lenz", "Schmitt", "Beck", "Wolff", "Schulze", "Maier", "Kern",
            "Berg", "Böhm", "Heinrich", "Brandt", "Schreiber", "Ziegler", "Kuhn", "Ludwig", "Winter", "Martin",
            "Kraemer", "Vogt", "Stein", "Jung", "Busch", "Albrecht", "Franke", "Simon", "Lorenz", "Ludwig",
            "Becker", "Schmitt", "Werner", "Schwarz", "Koch", "Hoffmann", "Schulz", "Fischer", "Meyer", "Wagner",
            "Bennett", "Brooks", "Butler", "Campbell", "Clark", "Collins", "Cook", "Cooper", "Cox", "Cruz",
            "Davis", "Diaz", "Edwards", "Evans", "Flores", "Foster", "Garcia", "Gonzalez", "Gray", "Green",
            "Griffin", "Hall", "Harris", "Hayes", "Henderson", "Hill", "Howard", "Hughes", "Jackson", "James",
            "Jenkins", "Johnson", "Jones", "Kelly", "King", "Lee", "Lewis", "Long", "Lopez", "Martin",
            "Martinez", "Miller", "Mitchell", "Moore", "Morgan", "Morris", "Murphy", "Myers", "Nelson", "Nguyen",
            "Ortiz", "Owens", "Parker", "Patterson", "Perez", "Perry", "Peterson", "Phillips", "Powell", "Price",
            "Ramirez", "Ramos", "Reed", "Reyes", "Reynolds", "Richardson", "Rivera", "Roberts", "Robinson", "Rodriguez",
            "Rogers", "Ross", "Ruiz", "Russell", "Ryan", "Sanchez", "Sanders", "Scott", "Shaw", "Simmons",
            "Simpson", "Smith", "Snyder", "Soto", "Stevens", "Sullivan", "Taylor", "Thomas", "Thompson", "Torres",
            "Tucker", "Turner", "Vasquez", "Wagner", "Walker", "Ward", "Warren", "Washington", "Watkins", "Watson",
            "Weaver", "Webb", "Wells", "West", "Wheeler", "White", "Williams", "Wilson", "Wood", "Woods",
            "Wright", "Young", "Zimmerman", "Abbott", "Acevedo", "Acosta", "Adkins", "Aguirre", "Ahmad", "Alexander",
            "Ali", "Allison", "Alston", "Anderson", "Andrews", "Anthony", "Armstrong", "Arnold", "Ashley", "Atkins",
            "Atkinson", "Austin", "Avery", "Avila", "Ayala", "Ayers", "Bailey", "Baird", "Baker", "Baldwin",
            "Ball", "Ballard", "Banks", "Barber", "Barker", "Barlow", "Barnes", "Barnett", "Barr", "Barrera",
            "Barrett", "Barron", "Barry", "Bartlett", "Barton", "Bass", "Bates", "Battle", "Bauer", "Baxter",
            "Beach", "Bean", "Beard", "Beasley", "Beck", "Becker", "Bell", "Bender", "Benjamin", "Benson",
            "Bentley", "Benton", "Berg", "Berger", "Bernard", "Berry", "Best", "Bird", "Bishop", "Black",
            "Blackburn", "Blackwell", "Blair", "Blake", "Blanchard", "Blankenship", "Blevins", "Bohrer", "Bolton", "Bond", "Bonner",
            "Booker", "Boone", "Booth", "Bowen", "Bowers", "Bowman", "Boyd", "Boyer", "Boyle", "Bradford",
            "Bradley", "Brady", "Branch", "Bray", "Brennan", "Brewer", "Bridges", "Briggs", "Bright", "Britt",
            "Brock", "Brock", "Brooks", "Broussard", "Brown", "Browning", "Bruce", "Bryan", "Bryant", "Buchanan",
            "Buck", "Buckley", "Buckner", "Bullard", "Burch", "Burgess", "Burke", "Burnett", "Burns", "Burton",
            "Bush", "Butler", "Byers", "Byrd", "Cabrera", "Cain", "Calderon", "Caldwell", "Calhoun", "Callahan",
            "Camacho", "Cameron", "Campbell", "Campos", "Cannon", "Cantrell", "Cardenas", "Carey", "Carlson", "Carpenter",
            "Carr", "Carroll", "Carson", "Carter", "Carver", "Case", "Casey", "Cash", "Castaneda", "Castillo",
            "Castro", "Cervantes", "Chambers", "Chan", "Chandler", "Chaney", "Chang", "Chapman", "Charles", "Chase",
            "Chavez", "Chen", "Cherry", "Christensen", "Christian", "Church", "Cisneros", "Clarke", "Clay", "Clayton",
            "Clements", "Clemons", "Cleveland", "Cline", "Cobb", "Cochran", "Coffey", "Cohen", "Cole", "Coleman",
            "Collier", "Collins", "Colon", "Combs", "Compton", "Conley", "Conner", "Conrad", "Contreras", "Conway",
            "Cook", "Cooke", "Cooley", "Cooper", "Copeland", "Cortez", "Cote", "Cotton", "Couch", "Cowan",
            "Cox", "Craft", "Craig", "Crane", "Crawford", "Crosby", "Cross", "Cruz", "Cummings", "Cunningham",
            "Curry", "Curtis", "Dale", "Dalton", "Daniel", "Daniels", "Daugherty", "Davenport", "David", "Davidson",
            "Davila", "Davis", "Dawson", "Day", "Decker", "Dejesus", "Delacruz", "Delaney", "Dennis", "Denton",
            "Diamond", "Dickerson", "Dickson", "Dillard", "Dillon", "Dixon", "Dodson", "Dominguez", "Donaldson", "Donovan",
            "Dorsey", "Dotson", "Douglas", "Downs", "Doyle", "Drake", "Dudley", "Duffy", "Duke", "Duncan",
            "Dunlap", "Dunn", "Duran", "Durham", "Dyer", "Eaton", "Edwards", "Elliott", "Ellis", "Ellison",
            "Emerson", "England", "English", "Erickson", "Escobar", "Espinoza", "Estes", "Estrada", "Evans", "Everett",
            "Ewing", "Farley", "Farmer", "Farrell", "Faulkner", "Ferguson", "Fernandez", "Ferrell", "Fields", "Figueroa",
            "Finley", "Fischer", "Fisher", "Fitzgerald", "Fitzpatrick", "Fleming", "Fletcher", "Flores", "Floyd", "Flynn",
            "Foley", "Forbes", "Ford", "Foreman", "Foster", "Fowler", "Fox", "Francis", "Franco", "Frank",
            "Franklin", "Frazier", "Frederick", "Freeman", "French", "Frost", "Fry", "Frye", "Fuller", "Fulton",
            "Gaines", "Gallagher", "Gallegos", "Galloway", "Gamble", "Garcia", "Gardner", "Garner", "Garrett", "Garrison",
            "Garza", "Gates", "Gay", "Gentry", "George", "Gibbs", "Gibson", "Gilbert", "Giles", "Gill",
            "Gillespie", "Gilliland", "Glass", "Glenn", "Glover", "Goff", "Golden", "Gomez", "Gonzales", "Gonzalez",
            "Good", "Goodman", "Goodwin", "Gordon", "Gould", "Graham", "Grant", "Graves", "Gray", "Green",
            "Greene", "Greer", "Gregory", "Griffin", "Griffith", "Grimes", "Gross", "Guerra", "Guerrero", "Guthrie",
            "Guy", "Guzman", "Hahn", "Hale", "Haley", "Hall", "Hamilton", "Hammond", "Hampton", "Hancock",
            "Haney", "Hansen", "Hanson", "Hardin", "Harding", "Hardy", "Harmon", "Harper", "Harrell", "Harrington",
            "Harris", "Harrison", "Hart", "Hartman", "Harvey", "Hatfield", "Hawkins", "Hayden", "Hayes", "Haynes",
            "Hays", "Head", "Heath", "Hebert", "Henderson", "Hendricks", "Hendrix", "Henry", "Hensley", "Henson",
            "Herman", "Hernandez", "Herrera", "Herring", "Hess", "Hewitt", "Hickman", "Hicks", "Higgins", "Hill",
            "Hines", "Hinton", "Hobbs", "Hodge", "Hodges", "Hoffman", "Hogan", "Holbrook", "Holden", "Holder",
            "Holland", "Holloway", "Holman", "Holmes", "Holt", "Hood", "Hooper", "Hoover", "Hopkins", "Horn",
            "Horne", "Horton", "House", "Houston", "Howard", "Howe", "Howell", "Hubbard", "Huber", "Hudson",
            "Huff", "Huffman", "Hull", "Humphrey", "Hunt", "Hunter", "Hurley", "Hurst", "Hutchinson", "Hyde",
            "Ingram", "Irwin", "Jackson", "Jacobs", "Jacobson", "James", "Jarvis", "Jefferson", "Jenkins", "Jennings",
            "Jensen", "Jimenez", "Johns", "Johnson", "Johnston", "Jones", "Jordan", "Joseph", "Joyce", "Joyner",
            "Juarez", "Justice", "Kane", "Kaufman", "Keith", "Keller", "Kelley", "Kelly", "Kemp", "Kennedy",
            "Kent", "Kerr", "Key", "Kidd", "Kim", "King", "Kinney", "Kirby", "Kirk", "Kirkland",
            "Klein", "Kline", "Knapp", "Knight", "Knowles", "Knox", "Koch", "Kramer", "Lacey", "Lamb",
            "Lambert", "Lancaster", "Landry", "Lane", "Lang", "Langley", "Lara", "Larsen", "Larson", "Lawrence",
            "Lawson", "Le", "Leach", "Leblanc", "Lee", "Leon", "Leonard", "Lester", "Levine", "Levy",
            "Lewis", "Lindsay", "Lindsey", "Little", "Livingston", "Lloyd", "Logan", "Long", "Lopez", "Lott",
            "Love", "Lowe", "Lowery", "Lucas", "Luna", "Lynch", "Lynn", "Lyons", "Macdonald", "Macias",
            "Mack", "Madden", "Maddox", "Maldonado", "Malone", "Mann", "Manning", "Marks", "Marquez", "Marsh",
            "Marshall", "Martin", "Martinez", "Mason", "Massey", "Mathews", "Mathis", "Matthews", "Maxwell", "May",
            "Mayer", "Maynard", "Mayo", "Mays", "McBride", "McCall", "McCarthy", "McCarty", "McClain", "McClure",
            "McConnell", "McCormick", "McCoy", "McDaniel", "McDonald", "McDowell", "McFadden", "McFarland", "McGee", "McGowan",
            "McGuire", "McIntosh", "McIntyre", "McKay", "McKee", "McKenzie", "McKnight", "McLaughlin", "McLean", "McLeod",
            "McMahon", "McMillan", "McNeil", "McPherson", "Meadows", "Medina", "Mejia", "Melendez", "Melton", "Mendez",
            "Mendoza", "Mercer", "Merrill", "Merritt", "Meyer", "Meyers", "Michael", "Middleton", "Miles", "Miller",
            "Mills", "Miranda", "Mitchell", "Molina", "Monroe", "Montgomery", "Montoya", "Moody", "Moon", "Mooney",
            "Moore", "Morales", "Moran", "Moreno", "Morgan", "Morin", "Morris", "Morrison", "Morrow", "Morse",
            "Morton", "Moses", "Mosley", "Moss", "Mueller", "Mullen", "Mullins", "Munoz", "Murillo", "Murphy",
            "Murray", "Myers", "Nash", "Navarro", "Neal", "Nelson", "Newman", "Newton", "Nguyen", "Nichols",
            "Nicholson", "Nielsen", "Nieves", "Nixon", "Noble", "Noel", "Nolan", "Norman", "Norris", "Norton",
            "Nunez", "O'Brien", "O'Connor", "O'Donnell", "O'Neill", "Ochoa", "Odom", "Odonnell", "Oliver", "Olsen",
            "Olson", "Oneal", "O'Neal", "Oneill", "O'Neill", "Orr", "Ortega", "Ortiz", "Osborn", "Osborne",
            "Owen", "Owens", "Pace", "Pacheco", "Padilla", "Page", "Palmer", "Park", "Parker", "Parks",
            "Parrish", "Parsons", "Pate", "Patel", "Patrick", "Patterson", "Patton", "Paul", "Payne", "Pearson",
            "Peck", "Pena", "Pennington", "Perez", "Perkins", "Perry", "Peters", "Petersen", "Peterson", "Petty",
            "Phelps", "Phillips", "Pickett", "Pierce", "Pittman", "Pitts", "Pollard", "Poole", "Pope", "Porter",
            "Potter", "Potts", "Powell", "Powers", "Pratt", "Preston", "Price", "Prince", "Pruitt", "Puckett",
            "Pugh", "Quinn", "Ramirez", "Ramos", "Randall", "Randolph", "Rasmussen", "Ratliff", "Ray", "Raymond",
            "Reed", "Reese", "Reeves", "Reid", "Reilly", "Reyes", "Reynolds", "Rhodes", "Rice", "Rich",
            "Richard", "Richards", "Richardson", "Richmond", "Riddle", "Riggs", "Riley", "Rios", "Rivas", "Roach",
            "Robbins", "Roberson", "Roberts", "Robertson", "Robinson", "Robles", "Rocha", "Rodgers", "Rodriguez", "Rogers",
            "Rojas", "Rollins", "Roman", "Romero", "Rosa", "Rosales", "Rosario", "Rose", "Ross", "Roth",
            "Rowe", "Rowland", "Roy", "Rubio", "Rush", "Russell", "Russo", "Rutledge", "Ryan", "Salas",
            "Salazar", "Salinas", "Sampson", "Sanchez", "Sanders", "Sandoval", "Sanford", "Santana", "Santiago", "Santos",
            "Sargent", "Saunders", "Savage", "Sawyer", "Schmidt", "Schneider", "Schroeder", "Schultz", "Schwartz", "Scott",
            "Sellers", "Serrano", "Sexton", "Shaffer", "Shannon", "Sharp", "Shaw", "Shelton", "Shepard", "Shepherd",
            "Sheppard", "Sherman", "Shields", "Short", "Silva", "Simmons", "Simon", "Simpson", "Sims", "Singleton",
            "Skinner", "Slater", "Sloan", "Small", "Smith", "Snider", "Snow", "Snyder", "Solis", "Solomon",
            "Sosa", "Soto", "Sparks", "Spears", "Spence", "Spencer", "Stafford", "Stanley", "Stanton", "Stark",
            "Steele", "Stein", "Stephens", "Stevens", "Stevenson", "Stewart", "Stokes", "Stone", "Stout", "Strickland",
            "Strong", "Stuart", "Suarez", "Sullivan", "Summers", "Sutton", "Swanson", "Sweeney", "Sweet", "Sykes",
            "Talley", "Tanner", "Tate", "Taylor", "Terrell", "Terry", "Thomas", "Thompson", "Thornton", "Tillman",
            "Todd", "Torres", "Townsend", "Tran", "Travis", "Trevino", "Trujillo", "Tucker", "Turner", "Tyler",
            "Tyson", "Underwood", "Valdez", "Valencia", "Valentine", "Valenzuela", "Vance", "Vang", "Vargas", "Vasquez",
            "Vaughan", "Vaughn", "Vazquez", "Vega", "Velasquez", "Velazquez", "Velez", "Villanueva", "Villarreal", "Villegas",
            "Vincent", "Vinson", "Wade", "Wagner", "Walker", "Wall", "Wallace", "Waller", "Walls", "Walsh",
            "Walter", "Walters", "Walton", "Ward", "Ware", "Warner", "Warren", "Washington", "Waters", "Watkins",
            "Watson", "Watts", "Weaver", "Webb", "Weber", "Webster", "Weeks", "Weiss", "Welch", "Wells",
            "West", "Wheeler", "Whitley", "Whitaker", "White", "Whitehead", "Whitfield", "Whitley", "Whitney", "Wiggins",
            "Wilcox", "Wilder", "Wiley", "Wilkerson", "Wilkins", "Wilkinson", "William", "Williams", "Williamson", "Willis",
            "Wilson", "Winters", "Wise", "Witt", "Wolf", "Wolfe", "Wong", "Wood", "Woodard", "Woods",
            "Woodward", "Wooten", "Workman", "Wright", "Wyatt", "Wynn", "Yang", "Yates", "York", "Young",
            "Zamora", "Zavala", "Zimmerman", "Zuniga"
        };

        /// <summary>
        /// Returns a unique random name (first + last). No repeats.
        /// Picks random first and random last until an unused combination is found.
        /// </summary>
        public static string GetRandomName()
        {
            lock (_rng)
            {
                for (int attempt = 0; attempt < 1000; attempt++)
                {
                    int fi = _rng.Next(FirstNames.Length);
                    int li = _rng.Next(LastNames.Length);
                    string name = $"{FirstNames[fi]} {LastNames[li]}";
                    if (_usedNames.Add(name))
                        return name;
                }
                // Fallback if we've used all 90k combos (extremely unlikely)
                return $"Skier {_rng.Next(100000, 999999)}";
            }
        }
    }
}
